version: '3.8'

services:
  # The Backend Service (your application)
  backend:
    # The image is dynamically set by the CI/CD pipeline
    image: ${DOCKERHUB_USERNAME}/petosapp-backend:${BACKEND_IMAGE_TAG:-latest}
    restart: always
    # The 'expose' instruction makes the port available to other services in the same network,
    # but not to the host machine. NGINX will connect to this.
    expose:
      - '3000' # Change to your application's actual port
    depends_on:
      - redis
    environment:
      # Add any environment variables your app needs to run
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  frontend:
    # The image is dynamically set by the CI/CD pipeline
    image: ${DOCKERHUB_USERNAME}/petosapp-frontend:${FRONTEND_IMAGE_TAG:-latest}
    restart: always
    # The 'expose' instruction makes the port available to other services in the same network,
    # but not to the host machine. NGINX will connect to this.
    expose:
      - '4173' # Change to your application's actual port
    environment:
      # Add any environment variables your app needs to run
      - VITE_BACKEND_URL=https://petosapp.ir/api

  # The Redis Service
  redis:
    image: 'redis:7-alpine'
    restart: always

  # The NGINX Reverse Proxy
  nginx:
    image: 'nginx:latest'
    restart: always
    ports:
      - '8888:80' # Maps port 80 on your server to port 80 in the NGINX container
      - '4443:443' # For future SSL/HTTPS
    volumes:
      # Mounts your custom NGINX config from the same directory on the server
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

networks:
  default:
    name: pet-plant-network
